name = "Hugo CMS"
license = "Apache License 2.0"
licenselink = "//github.com/Wachiwi/hugo-agency-theme/blob/master/LICENSE"
description = "A one page portfolio for companies and freelancers."
homepage = "//github.com/Wachiwi/hugo-agency-theme"
tags = ["cms", "company", "contact form", "simple", "google analytics", "piwik"]
min_version = 0.37.1

[author]
  name = "wachiwi"
  homepage = "//github.com/wachiwi"

# If porting an existing theme
[original]
  name = "David Miller"
  homepage = "//www.ironsummitmedia.com/"
  repo = "//github.com/IronSummitMedia/startbootstrap-agency"
